---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true
#configure_terminal: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockutil_install: true
# dockitems_remove: []
# dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

dotfiles_repo: https://github.com/SamuelNitsche/dotfiles
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .osx

homebrew_installed_packages:
  # Binaries
  - bash
  - bat
  - coreutils
  - ffmpeg
  - gh
  - git
  - grep
  - httpie
  - jq
  - mas
  - pkg-config
  - svn
  - thefuck
  # Media
  - jpegoptim
  - optipng
  - pngquant
  - svgo
  - gifsicle
  # Development
  - php
  - php@8.1
  - composer
  - imagemagick
  - meilisearch
  - mysql
  - nginx
  - redis
  - yarn

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/bundle
  - nicoverbruggen/homebrew-cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - dbngin
  - discord
  - docker
  - github
  - google-chrome
  - helo
  - insomnia
  - iterm2
  - phpmon
  - ray
  - tableplus
  - the-unarchiver
  - tinkerwell
  - tunnelbear
  - visual-studio-code
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: git-open
    state: present
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# oh-my-zsh
configure_oh_my_zsh: true
users:
  - username: samuelnitsche
    oh_my_zsh:
      theme: robbyrussell
      plugins:
        - git
        - laravel
      update_mode: reminder
      update_frequency: 3

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - scripts/link-custom-zsh-directory.yml
